name: Funcionalidade
description: Propor uma capacidade do editor
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema do usuário
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependências e impacto de desempenho
